# 文件路径 .github/workflows/deployment.yml
name: Deployment

on:
  push:
    branches: [main] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: deploy file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:  
        username: 'potatodev'
        server: '${{ secrets.SERVER_IP }}' 
        password: '${{ secrets.SSH_PASSWORD }}'
        local_path: './*'
        remote_path: '/www/wwwroot/akyuu-cn'
        delete_remote_files: true
