# 文件路径 .github/workflows/deployment.yml
name: Deployment

on:
  push:
    branches: [main] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.15.1'

    - name: Install dependencies & Generate static files
      run: |
        npm i -g hexo-cli
        npm i
        npm install hexo-generator-sitemap --save
        npm install hexo-generator-baidu-sitemap --save
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: EF
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/ltfjx/evershifting-fountain
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:pages
        
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
        ARGS: "-avz --delete"
        SOURCE: "public/"
        REMOTE_HOST: '${{ secrets.SERVER_IP }}'
        REMOTE_USER: 'root'
        TARGET: '/www/wwwroot/akyuu-cn'
