name: Hexo Deployment

on:
  push:
    branches: [main]

jobs:
  hexo-deployment:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.15.1'

    - name: Install dependencies & Generate static files
      run: |
        npm install --location=global hexo-cli
        npm i
        hexo clean
        hexo g
        
    - name: Deploy to Github Pages
      env:
        GIT_NAME: EF
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/akyuu-cn/evershifting-fountain
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./public && git init && git add .
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git commit -m "Site deployed by GitHub Actions"
        git push --force --quiet "https://$GH_TOKEN@$REPO" master:pages
        rm -rf ./.git
        
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
        REMOTE_HOST: '${{ secrets.SERVER_IP }}'
        REMOTE_USER: '${{ secrets.USER }}'
        REMOTE_PORT: '${{ secrets.PORT }}'
        TARGET: '/www/wwwroot/akyuu-cn'
        ARGS: "-avz --delete --chown=www:www"
        SOURCE: "public/" 